### ISSUE TITLE
pods in other namespaces are not visible

### ISSUE THREAD

**Issue by davcastroruiz** [predatorray/kubectl-tmux-exec#10]
https://github.com/predatorray/kubectl-tmux-exec/blob/93ac1a5af2e6a08f82abfb07876be58e407aec56/bin/kubectl-tmux_exec#L308

Hello! this plugin is awesome but I am using a lot of namespaces, --all should fix this.
`kubectl get po --all`

**Comment by predatorray** [comment]
Thanks @davcastroruiz for your proposal. Actually I have considered to implement this feature in the next release, which will allow you to set not only all namespaces `-A, --all-namespaces` but also a list of `--context` / `--namespace`.

Beside the line you mentioned, each namespace or context must be provided explicitly when pods are being `exec`-ed.

https://github.com/predatorray/kubectl-tmux-exec/blob/93ac1a5af2e6a08f82abfb07876be58e407aec56/bin/kubectl-tmux_exec#L323

It may take some effort to implement, but I hope it will be released soon.

**Comment by predatorray** [comment]
Hi, @davcastroruiz. The enhancement has been released in [the latest version](https://github.com/predatorray/kubectl-tmux-exec/releases/tag/v0.3.0). Now you can use the `--all-namespaces` or `--namespace` option to exec pods across multiple namespaces. Hope it will help you.

I will close the issue. If you have any other questions, please feel free to open another issue.

**Comment by davcastroruiz** [comment]
Thanks, a lot!
